CREATE TABLE `WMS`.`_inventory` (
	`InventoryID` BIGINT NOT NULL AUTO_INCREMENT,
	`BinID` BIGINT NOT NULL,
	`ProductID` BIGINT NOT NULL,
	`QTY` BIGINT NOT NULL,
  PRIMARY KEY (`InventoryID`),
  FOREIGN KEY (`ProductID`) 
	REFERENCES `_product`(`ProductID`)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (`BinID`) 
	REFERENCES `_bins`(`BinID`)
    ON UPDATE CASCADE ON DELETE RESTRICT);
